// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.10.0
// source: product/amazon.proto

package product

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// ========================================================================================
type ProductSKU struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// `json:"id"`
	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"id"`
	// `json:"asin"`
	ASIN string `protobuf:"bytes,2,opt,name=ASIN,proto3" json:"asin"`
	// `json:"price"`
	Price float32 `protobuf:"fixed32,3,opt,name=Price,proto3" json:"price"`
	// `json:"seller"`
	Seller string `protobuf:"bytes,4,opt,name=Seller,proto3" json:"seller"`
	// `json:"instock"`
	Instock bool `protobuf:"varint,5,opt,name=Instock,proto3" json:"instock"`
	// `json:"available"`
	Active bool `protobuf:"varint,6,opt,name=Active,proto3" json:"available"`
	// `json:"createdonutc"`
	CreatedOnUTC string `protobuf:"bytes,7,opt,name=CreatedOnUTC,proto3" json:"createdonutc"`
}

func (x *ProductSKU) Reset() {
	*x = ProductSKU{}
	if protoimpl.UnsafeEnabled {
		mi := &file_product_amazon_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProductSKU) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductSKU) ProtoMessage() {}

func (x *ProductSKU) ProtoReflect() protoreflect.Message {
	mi := &file_product_amazon_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductSKU.ProtoReflect.Descriptor instead.
func (*ProductSKU) Descriptor() ([]byte, []int) {
	return file_product_amazon_proto_rawDescGZIP(), []int{0}
}

func (x *ProductSKU) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *ProductSKU) GetASIN() string {
	if x != nil {
		return x.ASIN
	}
	return ""
}

func (x *ProductSKU) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ProductSKU) GetSeller() string {
	if x != nil {
		return x.Seller
	}
	return ""
}

func (x *ProductSKU) GetInstock() bool {
	if x != nil {
		return x.Instock
	}
	return false
}

func (x *ProductSKU) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *ProductSKU) GetCreatedOnUTC() string {
	if x != nil {
		return x.CreatedOnUTC
	}
	return ""
}

var File_product_amazon_proto protoreflect.FileDescriptor

var file_product_amazon_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x2f, 0x61, 0x6d, 0x61, 0x7a, 0x6f, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x22,
	0xb4, 0x01, 0x0a, 0x0a, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x53, 0x4b, 0x55, 0x12, 0x0e,
	0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x12,
	0x0a, 0x04, 0x41, 0x53, 0x49, 0x4e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x41, 0x53,
	0x49, 0x4e, 0x12, 0x14, 0x0a, 0x05, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x05, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x65, 0x6c, 0x6c,
	0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x65, 0x6c, 0x6c, 0x65, 0x72,
	0x12, 0x18, 0x0a, 0x07, 0x49, 0x6e, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x49, 0x6e, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x63,
	0x74, 0x69, 0x76, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x41, 0x63, 0x74, 0x69,
	0x76, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x4f, 0x6e, 0x55,
	0x54, 0x43, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x4f, 0x6e, 0x55, 0x54, 0x43, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x79, 0x6e, 0x63, 0x66, 0x75, 0x74, 0x75, 0x72, 0x65, 0x2f,
	0x73, 0x70, 0x69, 0x64, 0x65, 0x72, 0x73, 0x2f, 0x61, 0x6d, 0x61, 0x7a, 0x6f, 0x6e, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_product_amazon_proto_rawDescOnce sync.Once
	file_product_amazon_proto_rawDescData = file_product_amazon_proto_rawDesc
)

func file_product_amazon_proto_rawDescGZIP() []byte {
	file_product_amazon_proto_rawDescOnce.Do(func() {
		file_product_amazon_proto_rawDescData = protoimpl.X.CompressGZIP(file_product_amazon_proto_rawDescData)
	})
	return file_product_amazon_proto_rawDescData
}

var file_product_amazon_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_product_amazon_proto_goTypes = []interface{}{
	(*ProductSKU)(nil), // 0: product.ProductSKU
}
var file_product_amazon_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_product_amazon_proto_init() }
func file_product_amazon_proto_init() {
	if File_product_amazon_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_product_amazon_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProductSKU); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_product_amazon_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_product_amazon_proto_goTypes,
		DependencyIndexes: file_product_amazon_proto_depIdxs,
		MessageInfos:      file_product_amazon_proto_msgTypes,
	}.Build()
	File_product_amazon_proto = out.File
	file_product_amazon_proto_rawDesc = nil
	file_product_amazon_proto_goTypes = nil
	file_product_amazon_proto_depIdxs = nil
}
